### ISSUE TITLE
How to extract result from given object to the Html Output

### ISSUE THREAD

**Issue by AGK93** [mcychan/GASchedule.cs#1]
Hello,

I am using this project for class scheduling solution and I don't want to use HTML as the final response.
I am trying to figure out the object that given to the HTML response (alg.Result). Can anyone explain how to extract the result from this JSON object given to HtmlOutput

`var htmlResult = HtmlOutput.GetResult(alg.Result);`

below you can find the result in the JSON format from `alg.Result` object [algResult.txt](https://github.com/mcychan/GASchedule.cs/files/7949213/algResult.txt)

~ 

If I can understand the solution, I will contribute and make the feature for sending result through API to make more multi usable and user friendly to be used from anywhere

@mcychan

**Comment by mcychan** [comment]
I updated README.md.
Please help to improve [JsonOutput.cs](https://raw.githubusercontent.com/mcychan/GASchedule.cs/master/GaSchedule.Console/JsonOutput.cs)

**Comment by AGK93** [comment]
I can create the function that result can be sended through API to the specific endpoint

for example: `ApiModel.sendResult(alg.Result,"/api/specific_end_point");`

what do you think about it ? @mcychan

**Comment by mcychan** [comment]
That means you would like to add a new project called GaSchedule.OpenApi
Showing the Rest API with additional nuget packages and dependencies

**Comment by AGK93** [comment]
no no, i will add some classes for api, i think i can do it also send GaSchedule.json through API in the same format,users do not need to add file to the project manually

p.s

```
Class ApiModel

function sendResult(alg.Result,"/api/specific_end_point"){
           // send result in specific end point
}

function GetConfigurationFile("api/get_file"){
         // read json file from this API and send to the algorithm same as parsing file
}
```


@mcychan

**Comment by mcychan** [comment]
Sorry, I'm not familiar with the latest REST APIs with .NET
I can do the Rest API in java.
You may refer to [OpenApi.java](https://raw.githubusercontent.com/mcychan/GASchedule.j2se/master/src/hk/edu/gaSchedule/OpenApi.java) and [test.html](https://raw.githubusercontent.com/mcychan/GASchedule.j2se/master/test.html)

**Comment by AGK93** [comment]
You don't need to do anything, I will make it for your project (contribute). I will create a pull request for this task also I will explain on read_me file how to use it.

@mcychan
